name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/atuline/WLED/archive/refs/heads/dev.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:soundReactive_esp32dev' >>platformio.ini
        echo 'build_flags = ${env:soundReactive_esp32dev.build_flags} -D MIC_LOGGER -D WLED_ENABLE_PIXART -D LEDPIN=2 -D BTNPIN=35 -D AUDIOPIN=33 -D CLIENT_SSID='\''"vannwireless"'\'' -D USERMOD_DHT -D USERMOD_DHT_CELSIUS -D USERMOD_AUTO_SAVE -D USERMOD_FOUR_LINE_DISPLAY -D USERMOD_ROTARY_ENCODER_UI -D USERMOD_MODE_SORT -D USE_ALT_DISPlAY -D USERMOD_PWM_OUTPUTS -D USERMOD_SSDR -D USERMOD_SN_PHOTORESISTOR' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:soundReactive_esp32dev.lib_deps}' >>platformio.ini
        echo '  https://github.com/alwynallan/DHT_nonblocking' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  olikraus/U8g2 @ ^2.28.8' >>platformio.ini
        echo '  Wire' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
